### ISSUE TITLE
Bungee - way to read tags off other servers

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#50]
I imagine something like
`- ~bungee read_tag server:PotatoLand tag:server.flag[potatoCount] save:myPotatoes`
`- announce "<entry[myPotatoes].result> potatoes left before the famine!"`

**Comment by mcmonkey4eva** [comment]
oh and an optional `blocking` arg or somesuch to not require the ~

**Comment by mcmonkey4eva** [comment]
Perhaps a config-option to enable a tag that allows directly reading, EG `<bunge[seerver].tag[server.flag[potatocount]]>` but disabled by default with a security/speed warning

**Comment by Morphan1** [comment]
Hmm...
`bungee [<server>|...] (<commands>) (read_tag [tag:<tag>])`
how would actual meta for basically that look?
and yeah, that sounds reasonable

**Comment by mcmonkey4eva** [comment]
Perhaps breaking all you hold dear and making it /two separate/ commands :o : o :ooooo
Or, `bungee [<server>|...] [<commands>/read_tag:<tag>]` or something like that

**Comment by Morphan1** [comment]
I was thinking of two commands...`BungeeTag command!`

**Comment by Morphan1** [comment]
So... This is possible now. I'll add documentation for the command soon, but for now, here's an example:
```
testbungeetask:
  type: task
  script:
  - ~bungeetag <server.flag[potato]> "server:server@Test" "save:tag"
  - announce <entry[tag].result>
```
